---
# User some changes will be applied to, e.g. zshrc configuration etc. 
target_username: rafaelktistakis
# Changes to be made to the config.txt file.
config_txt_changes:
  # Enable USB OTG mode.
  - option: dtoverlay
    value: dwc2
  # Set frame buffer width.
  - option: framebuffer_width
    value: 1024
  # Set frame buffer height.
  - option: framebuffer_height
    value: 768

users_shell_changes:
  - option: rafaelktistakis
    value: zsh
  - option: root
    value: bash

tasks_to_include:
#  - hardening
#  - usbc-gadget
#  - docker-setup.yml
