---
- hosts: pi
  become: yes
  gather_facts: true
  ignore_errors: yes

- name: OS Hardening devsec
  hosts: pi
  become: yes
  collections:
#    - devsec.hardening
  roles:
    # - core
#    - os_hardening
#    - ssh_hardening

  vars_files:
    - config.yml

  pre_tasks:
    - name: verify git installation.
      package: name=git state=present

  tasks:
#    - name: Installing and adjusting different core utilities
#     become: yes
#    import_tasks: playbooks/core.yml
#    - name: usbc gadget setup
#      become: yes
#      import_tasks: playbooks/usbc-gadget.yml
#    - name: docker setup
#      become: yes
#      import_tasks: playbooks/docker-setup.yml
#    - name: plex setup
#      become: yes
#      import_tasks: playbooks/plex-setup.yml
#    - name: rtorrent setup
#      become: yes
#      import_tasks: playbooks/qbittorrent-setup.yml
#    - name: external mount permissions
#      become: yes
#      import_tasks: playbooks/external-mount-setup.yml
   - name: Starship setup
     become: yes
     import_tasks: playbooks/starship-setup.yml
#    - name: Tmux setup
#      become: yes
#      import_tasks: playbooks/tmux-setup.yml
  #  - name: Homebridge setup
  #    become: yes
  #    import_tasks: playbooks/homebridge-setup.yml
    # - name: Code Server (self-hosted)
    #   become: yes
    #   import_tasks: playbooks/code-tunnel-server-setup.yml
