---
- hosts: pi
  become: yes
  gather_facts: true
  ignore_errors: yes

#- name: OS Hardening devsec
#  become: yes
#  collections:
#    - devsec.hardening
#  roles:
#    - os_hardening
#    - ssh_hardening

  vars_files:
    - config.yml

  pre_tasks:
    - name: verify git installation.
      package: name=git state=present

  tasks:
#    - name: hardening
#      become: yes
#      import_tasks: playbooks/hardening.yml
#    - name: usbc gadget setup
#      become: yes
#      import_tasks: playbooks/usbc-gadget.yml
#    - name: docker setup
#      become: yes
#      import_tasks: playbooks/docker-setup.yml
#    - name: plex setup
#      become: yes
#      import_tasks: playbooks/plex-setup.yml
    - name: rtorrent setup
      become: yes
      import_tasks: playbooks/qbittorrent-setup.yml
