---
- name: Install Code Server package
  apt:
    state: present
    update_cache: true
    name: "{{ packages }}"
  vars:
    packages:
    - code-server

# Look codeserver script under include, for running the server
# Current configuration should not be exposed to web as no-auth and no-cert has been configured
# Only for local dev.

- name: Copy codeserver command prompt
  copy:
    src: ./include/codeserver.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    backup: no
