
---
#- name: OS Hardening devsec
#  become: yes
#  collections:
#    - devsec.hardening
#  roles:
#    - os_hardening
#    - ssh_hardening

- name: Upgrade all packages
  apt:
    name: '*'
    update_cache: true
    autoremove: true
    state: latest

- name: Install packages
  apt:
    state: present
    update_cache: true
    name: "{{ packages }}"
  vars:
    packages:
    - screen
    - tmux
    - vim
    - snapd
#      - etckeeper
    - git
    - dnsmasq
    - exfat-fuse
    - exfat-utils
    - unrar
    - zsh
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
    - fonts-firacode

- name: Snap packages
  snap:
    name:
      - core
      - snap-store
    state: present
    channel: latest/edge

      
- name: Copy screenrc
  copy:
    src: ./include/screenrc
    dest: /etc/screenrc
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Copy .zshrc
  copy:
    src: ./include/.zshrc
    dest: /home/{{ target_username }}/.zshrc
    owner: "{{ target_username }}"
    group: "{{ target_username }}"
    mode: 0644
    backup: yes

- name: Copy isThrottled
  copy:
    src: ./include/isThrottled.sh
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
    backup: no

- name: change user shell to zsh 
  user:
    name: "{{ item.option }}"
    shell: /bin/{{ item.value }}
  with_items: '{{ users_shell_changes }}'

- name: Overclocking the little Pi
  blockinfile:
    path: /boot/config.txt
    create: false
    state: present
    insertafter: "arm_freq"
    mode: 0755
    block: |
      over_voltage=2
      arm_freq=1800
#      If you want to get crazy try alternatively the below values instead
#      over_voltage=6
#      arm_freq=2147
#      gpu_freq=750

- name: Enable VNC
  shell: "raspi-config nonint do_vnc 0"
  changed_when: false

- name: Set Boot behaviour
  shell: "raspi-config nonint do_boot_behaviour {{ BOOTBEHAVIOUR }}"
  changed_when: false
